# Generated by Django 4.1.1 on 2022-09-16 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('link', models.CharField(max_length=500, null=True)),
                ('description', models.FileField(default=None, null=True, upload_to='description/')),
                ('source_code', models.FileField(default=None, null=True, upload_to='source_code/')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_list.difficulty')),
            ],
        ),
    ]
