# Generated by Django 4.1.1 on 2022-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
