# Generated by Django 4.1.1 on 2022-10-07 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0003_topic_remove_problem_topic_problem_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
