# Generated by Django 4.1.1 on 2022-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0004_problem_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
