# Generated by Django 4.1.1 on 2022-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0006_remove_problem_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
