# Generated by Django 4.1.1 on 2022-10-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0007_remove_problem_description_problem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
