# Generated by Django 4.1.1 on 2022-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0008_alter_difficulty_id_alter_problem_id_alter_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='topics',
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
