# Generated by Django 4.1.1 on 2022-10-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0009_remove_problem_topics_problem_topic_delete_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
