# Generated by Django 4.1.1 on 2022-10-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0010_alter_difficulty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='difficulty',
            new_name='foreign_key_to_difficulty',
        ),
    ]
