# Generated by Django 4.1.1 on 2022-10-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0011_rename_difficulty_problem_foreign_key_to_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='foreign_key_to_difficulty',
            new_name='difficulty',
        ),
    ]
