# Generated by Django 4.1.1 on 2022-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0013_topic_remove_problem_topic_problem_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
