# Generated by Django 4.1.1 on 2022-10-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0014_remove_problem_topic_delete_topic_problem_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, max_length=256, unique=True)),
                ('leetcode_github', models.URLField(blank=True, max_length=256, unique=True)),
                ('medium', models.URLField(blank=True, max_length=256, unique=True)),
                ('linked_in', models.URLField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.URLField(blank=True, max_length=256, unique=True),
        ),
    ]
