# Generated by Django 4.1.1 on 2022-10-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0017_problem_mote_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='mote_img',
        ),
    ]
