# Generated by Django 4.1.2 on 2022-10-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_list', '0018_remove_problem_mote_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='img/'),
        ),
    ]
